### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by ivalaginja**
This has been confusing the crap out of me while working with different conda environments.

### CODE REVIEW

**Comment by jamienoss** [comment]
I felt like changing this too, a while back. Just be aware that this doesn't work with a dev install, which is what we tend to use. ``conda list`` will show you only that when installed not when a new branch/tag is checked out.

**Comment by ivalaginja** [comment]
@jamienoss are you sure? I just tried it on spacetelescope/pastis (branch beyond/package-setup), where I also install with dev and there conda list shows me what's in the setup.py

**Comment by jamienoss** [comment]
Lol not now I'm not. I had tried it again too, with this very branch and it didn't work as it hadn't done before.

What exactly did you do?

**Comment by ivalaginja** [comment]
I did `cd instrument-interface-library` and then ran this:

Screenshot 2020-09-14 at 16 37 42

The `conda list` shows me `catkit 0.13.0` now.

**Comment by ivalaginja** [comment]
Of course this would not work if v0.13.0 or anything before is checked out since the version of the `setup.py` it contains won't have this update included. Which also means that this needs to be updated with every new release otherwise it's not fixed at all, and this PR here won't fix it either.

**Comment by jamienoss** [comment]
@ivalaginja ok, that's what I thought you would have done. So if you re-install it as you did then it will obviously work. However, the point of the dev install is that you don't reinstall it every time you check out a new branch.

**Comment by ivalaginja** [comment]
Correct, but it will at least show up as the most recent release from which you installed initially as opposed to one from over a year ago, as long as this gets updated along with every release. So as I said, this PR won't fix anything per se, but might reduce confusion as to why your catkit installation shows up as older than this frickin' pandemic.

**Review by jamienoss — APPROVED** [review]

**Comment by jamienoss** [comment]
@ivalaginja For sure, I wasn't saying that we don't do this just to be mindful of its limitations, that this too can easily yield the same confusion as the scenario that lead you to open this PR.

**Pull request merged**
